### ISSUE TITLE
`MultivariateOptimizationResults` depwarn

### ISSUE THREAD

**Issue by ianshmean** [JuliaNLSolvers/LsqFit.jl#42]
I tried to fix this by adding a false to `MultivariateOptimizationResults` but it still depwarns

https://github.com/ianshmean/LsqFit.jl/commit/b3391a1ca6608209355206dd7c5dd0edf8490d18

```
WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,h_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,false,trace,f_calls,g_calls,h_calls) instead.
```

**Comment by blakejohnson** [comment]
Dupe of #31 and #33? At any rate, I cannot reproduce this on master (f16f605). What has changed since you opened #33?

**Comment by ianshmean** [comment]
Sorry, I should've appended to #33 
Both LsqFit and Optim are master on two different 0.5.0 setups I use, and both show the depwarning

**Comment by blakejohnson** [comment]
That extra `false` for the `f_increased` parameter is already there on LsqFit master.

**Comment by ianshmean** [comment]
So, the second mistake I made.. was thinking I hadn't forked this repo before.. so was working off an older version yesterday when I thought I'd just done a fresh fork. Ignore my blundering, please..

I'm comparing the use of MultivariateOptimizationResults to try and get to the bottom of this.

```
MultivariateOptimizationResults(method,			initial_x,	minimizer,	minimum,	iterations,	iteration_converged,	x_converged,	x_tol,	f_converged,	f_tol,	g_converged,	g_tol,	false,	trace,	f_calls,	g_calls,	h_calls)
MultivariateOptimizationResults("Levenberg-Marquardt", 	initial_x, 	x, 		sumabs2(fcur), 	iterCt, 	!converged, 		x_converged, 	0.0, 	false, 		0.0, 	g_converged, 	tolG, 	false, 	tr, 	f_calls, 	g_calls, 	0)
```

**Comment by blakejohnson** [comment]
I just pushed a commit that annotates the inputs to that constructor for the same reason. I'm not seeing what's wrong.

**Comment by ianshmean** [comment]
Good move. It's still occurring with LsqFit and Optim masters. 

I even just deleted my `.julia` and reinstalled from scratch, ensuring LsqFit and Optim were free'd first.
 
Very confused...

```
WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,h_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,false,trace,f_calls,g_calls,h_calls) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{LsqFit.LevenbergMarquardt},1}, ::Int64, ::Int64, ::Int64) at ./deprecated.jl:50
 in #levenberg_marquardt#1(::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::LsqFit.#f#4{splash.#model#41,Array{Float64,1},Array{Float64,1}}, ::Calculus.#g#5{LsqFit.#f#4{splash.#model#41,Array{Float64,1},Array{Float64,1}},Symbol}, ::Array{Float64,1}) at /Users/IanB/.julia/v0.5/LsqFit/src/levenberg_marquardt.jl:169
 in #lmfit#2(::Array{Any,1}, ::Function, ::LsqFit.#f#4{splash.#model#41,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}) at /Users/IanB/.julia/v0.5/LsqFit/src/curve_fit.jl:30
 in #curve_fit#3(::Array{Any,1}, ::Function, ::splash.#model#41, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/IanB/.julia/v0.5/LsqFit/src/curve_fit.jl:40
....
```

```
julia> Pkg.status()
18 required packages:
 - DSP                           0.1.1
 - DataFrames                    0.8.5
 - DataStructures                0.5.2
 - HttpParser                    0.2.0
 - HypothesisTests               0.4.0
 - IJulia                        1.4.1
 - Images                        0.7.0
 - JSON                          0.8.3
 - LibBSON                       0.2.8
 - LsqFit                        0.1.1+             master
 - MbedTLS                       0.4.3
 - Mongo                         0.2.3
 - Plots                         0.10.3
 - ProgressMeter                 0.3.3
 - PyCall                        1.10.0
 - PyPlot                        2.3.1
 - Requests                      0.4.1
 - ZipFile                       0.3.0
73 additional packages:
 - AxisArrays                    0.0.3
 - BinDeps                       0.4.5
 - BufferedStreams               0.3.0
 - Calculus                      0.2.0
 - CatIndices                    0.0.1
 - Codecs                        0.2.0
 - ColorTypes                    0.3.4
 - ColorVectorSpace              0.3.1
 - Colors                        0.7.3
 - Combinatorics                 0.3.2
 - Compat                        0.18.0
 - ComputationalResources        0.0.1
 - Conda                         0.5.1
 - CustomUnitRanges              0.0.3
 - DataArrays                    0.3.12
 - DiffBase                      0.0.4
 - Distributions                 0.12.0
 - FFTViews                      0.0.1
 - FileIO                        0.3.0
 - FixedPointNumbers             0.3.3
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.3.4
 - GZip                          0.2.20
 - Graphics                      0.1.3
 - Hiccup                        0.1.1
 - Homebrew                      0.4.2
 - HttpCommon                    0.2.6
 - ImageAxes                     0.1.0
 - ImageCore                     0.1.2
 - ImageFiltering                0.1.1
 - ImageMetadata                 0.2.0
 - IndirectArrays                0.1.0
 - IntervalSets                  0.0.2
 - Iterators                     0.2.0
 - Juno                          0.2.6
 - LaTeXStrings                  0.2.0
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - MacroTools                    0.3.4
 - MappedArrays                  0.0.5
 - Measures                      0.0.3
 - Media                         0.2.5
 - NaNMath                       0.2.2
 - Nettle                        0.2.4
 - OffsetArrays                  0.2.13
 - Optim                         0.7.5+             master
 - PDMats                        0.5.6
 - PlotThemes                    0.1.1
 - PlotUtils                     0.3.0
 - PolynomialFactors             0.0.3
 - Polynomials                   0.1.2
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.2
 - QuadGK                        0.1.1
 - RangeArrays                   0.1.1
 - RecipesBase                   0.1.0
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - Roots                         0.3.0
 - SHA                           0.3.1
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SimpleTraits                  0.2.0
 - SortingAlgorithms             0.1.0
 - SpecialFunctions              0.1.0
 - StaticArrays                  0.2.1
 - StatsBase                     0.13.1
 - StatsFuns                     0.4.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.1
 - URIParser                     0.1.8
 - ZMQ                           0.4.1
```

**Comment by ianshmean** [comment]
It seems it's resolved. I can't say specifically what solved it, but I'm guessing that for some reason the package wasn't being built properly, as the src files were accurate to master.

**Comment by blakejohnson** [comment]
Strange.

**Comment by rand5** [comment]
I just checked out the master and am having a similar issue-- calling `curve_fit` produces
`WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,h_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,false,trace,f_calls,g_calls,h_calls) instead.`

**Comment by pkofod** [comment]
More info would be useful, including: `Pkg.status()`, `versioninfo()` and the full info around the warning you got.

**Comment by rand5** [comment]
`Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)`



26 required packages:
 - BenchmarkTools                0.0.7
 - Changepoints                  0.2.0
 - Clustering                    0.7.0
 - DSP                           0.1.1
 - DataFrames                    0.8.5
 - Dierckx                       0.2.0
 - GLM                           0.6.1
 - GR                            0.19.0
 - GeometricalPredicates         0.0.6
 - Gtk                           0.10.4+            master
 - IJulia                        1.4.1
 - ImageFiltering                0.1.2
 - ImageMagick                   0.2.1
 - ImageView                     0.3.1
 - Images                        0.7.0
 - Immerse                       0.0.12
 - LsqFit                        0.1.1+             master
 - MultivariateStats             0.3.1
 - NLopt                         0.3.3
 - PlotlyJS                      0.5.2+             master
 - Plots                         0.10.3
 - PyCall                        1.10.0
 - PyPlot                        2.3.1
 - Rsvg                          0.0.2+             master
 - StatPlots                     0.2.1
 - UnicodePlots                  0.2.3
105 additional packages:
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.0.3
 - BaseTestNext                  0.2.2
 - BinDeps                       0.4.7
 - Blink                         0.5.1
 - Blosc                         0.2.0
 - BufferedStreams               0.3.0
 - Cairo                         0.2.35
 - Calculus                      0.2.0
 - CatIndices                    0.0.2
 - Codecs                        0.2.0
 - ColorTypes                    0.3.4
 - ColorVectorSpace              0.4.0
 - Colors                        0.7.3
 - Compat                        0.19.0
 - Compose                       0.4.5
 - ComputationalResources        0.0.2
 - Conda                         0.5.1
 - Contour                       0.2.0
 - CustomUnitRanges              0.0.4
 - DataArrays                    0.3.12
 - DataStructures                0.5.2
 - Dates                         0.4.4
 - DiffBase                      0.0.4
 - Distances                     0.4.0
 - Distributions                 0.12.1
 - DocStringExtensions           0.3.1
 - DualNumbers                   0.2.3
 - FFTViews                      0.0.1
 - FileIO                        0.3.0
 - FixedPointNumbers             0.3.4
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.3.4
 - GZip                          0.2.20
 - Gadfly                        0.5.3
 - Graphics                      0.1.3
 - GtkUtilities                  0.2.0
 - HDF5                          0.7.3
 - Hexagons                      0.0.4
 - Hiccup                        0.1.1
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - ImageAxes                     0.1.0
 - ImageCore                     0.1.4
 - ImageMetadata                 0.2.0
 - IndirectArrays                0.1.1
 - IniFile                       0.2.5
 - Interpolations                0.3.7
 - IntervalSets                  0.0.3
 - Iterators                     0.3.0
 - JLD                           0.6.9
 - JSON                          0.8.3
 - Juno                          0.2.6
 - KernelDensity                 0.3.0
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LegacyStrings                 0.2.0
 - LibExpat                      0.2.4
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - Loess                         0.1.0
 - MacroTools                    0.3.4
 - MappedArrays                  0.0.6
 - MathProgBase                  0.6.1
 - MbedTLS                       0.4.3
 - Measures                      0.0.3
 - Media                         0.2.5
 - Mustache                      0.1.3
 - Mux                           0.2.3
 - NaNMath                       0.2.2
 - NearestNeighbors              0.0.5
 - Nettle                        0.3.0
 - OffsetArrays                  0.2.14
 - Optim                         0.7.7
 - PDMats                        0.5.6
 - PlotThemes                    0.1.1
 - PlotUtils                     0.3.0
 - Polynomials                   0.1.2
 - PositiveFactorizations        0.0.4
 - QuadGK                        0.1.1
 - RangeArrays                   0.1.2
 - Ratios                        0.0.4
 - RecipesBase                   0.1.0
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - SHA                           0.3.1
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SimpleTraits                  0.3.0
 - SortingAlgorithms             0.1.0
 - SpecialFunctions              0.1.1
 - StaticArrays                  0.2.1
 - StatsBase                     0.13.1
 - StatsFuns                     0.4.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.2
 - Tk                            0.4.0
 - URIParser                     0.1.8
 - WebSockets                    0.2.1
 - WinRPM                        0.2.3
 - Winston                       0.12.1
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.4.1


Full warning:

`WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,h_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,false,trace,f_calls,g_calls,h_calls) instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{LsqFit.LevenbergMarquardt},1}, ::Int64, ::Int64, ::Int64) at .\deprecated.jl:50
 in #levenberg_marquardt#1(::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::LsqFit.#f#4{#model#8,Array{Float64,1},Array{Float64,1}}, ::Calculus.#g#5{LsqFit.#f#4{#model#8,Array{Float64,1},Array{Float64,1}},Symbol}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\levenberg_marquardt.jl:169
 in #lmfit#2(::Array{Any,1}, ::Function, ::LsqFit.#f#4{#model#8,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\curve_fit.jl:30
 in #curve_fit#3(::Array{Any,1}, ::Function, ::#model#8, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\curve_fit.jl:40
 in #Org_LinFit_csv_LsqFit_multifile#7(::Int64, ::Int64, ::Bool, ::Function, ::String) at C:\Users\Cm7045\Org_LinFit_csv_LsqFit_multifile.jl:63
 in (::#kw##Org_LinFit_csv_LsqFit_multifile)(::Array{Any,1}, ::#Org_LinFit_csv_LsqFit_multifile, ::String) at .\<missing>:0
 in include_string(::String, ::String) at .\loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Cm7045\.julia\v0.5\IJulia\src\execute_request.jl:157
 in eventloop(::ZMQ.Socket) at C:\Users\Cm7045\.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##13#19)() at .\task.jl:360
while loading In[35], in expression starting on line 1`

**Comment by blakejohnson** [comment]
I wonder if this is some cache invalidation problem on windows? Try deleting Optim.ji and LsqFit.ji from your `.julia/lib/v0.5/` folder.

**Comment by rand5** [comment]
Not having any luck with that-- same warning:

> `WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,h_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,false,trace,f_calls,g_calls,h_calls) instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{LsqFit.LevenbergMarquardt},1}, ::Int64, ::Int64, ::Int64) at .\deprecated.jl:50
 in #levenberg_marquardt#1(::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::LsqFit.#f#4{#model#2,Array{Float64,1},Array{Float64,1}}, ::Calculus.#g#5{LsqFit.#f#4{#model#2,Array{Float64,1},Array{Float64,1}},Symbol}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\levenberg_marquardt.jl:169
 in #lmfit#2(::Array{Any,1}, ::Function, ::LsqFit.#f#4{#model#2,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\curve_fit.jl:30
 in #curve_fit#3(::Array{Any,1}, ::Function, ::#model#2, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\Cm7045\.julia\v0.5\LsqFit\src\curve_fit.jl:40
 in #Org_LinFit_csv_LsqFit_multifile#1(::Int64, ::Int64, ::Bool, ::Bool, ::Function, ::String) at C:\Users\Cm7045\Org_LinFit_csv_LsqFit_multifile.jl:66
 in (::#kw##Org_LinFit_csv_LsqFit_multifile)(::Array{Any,1}, ::#Org_LinFit_csv_LsqFit_multifile, ::String) at .\<missing>:0
 in include_string(::String, ::String) at .\loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Cm7045\.julia\v0.5\IJulia\src\execute_request.jl:157
 in eventloop(::ZMQ.Socket) at C:\Users\Cm7045\.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##13#19)() at .\task.jl:360
while loading In[3], in expression starting on line 1`

**Comment by ianshmean** [comment]
I don't know when this was specifically fixed for me, but try building explicitly. 
My guess is it is a build cache update issue

**Comment by rand5** [comment]
Thanks for the suggestion but still no luck. I'll post if it ever sorts itself out.
